services: 
  db:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      #credentials are stored in the .env fileports:
      
      ports:
        - "5432:5432" # external:internal
      volumes:
        - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {} #pgdata is not a folder but a Docker volume
 